apiVersion: v1
kind: Service
metadata:
  name: shark-mqtt
  namespace: shark-mqtt
  labels:
    app.kubernetes.io/name: shark-mqtt
    app.kubernetes.io/component: broker
spec:
  selector:
    app.kubernetes.io/name: shark-mqtt
    app.kubernetes.io/component: broker
  ports:
    - name: mqtt
      protocol: TCP
      port: 1883
      targetPort: 1883
    - name: metrics
      protocol: TCP
      port: 9090
      targetPort: 9090
  type: ClusterIP
