apiVersion: v1
kind: Service
metadata:
  name: {{ include "shark-mqtt.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "shark-mqtt.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "shark-mqtt.selectorLabels" . | nindent 4 }}
  ports:
    - name: mqtt
      protocol: TCP
      port: {{ .Values.service.mqttPort }}
      targetPort: mqtt
    - name: metrics
      protocol: TCP
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
