apiVersion: v1
kind: Service
metadata:
  name: shark-mqtt
  namespace: shark-mqtt
  labels:
    app: shark-mqtt
spec:
  selector:
    app: shark-mqtt
  ports:
    - name: mqtt
      protocol: TCP
      port: 1883
      targetPort: 1883
    - name: health
      protocol: TCP
      port: 9090
      targetPort: 9090
  type: ClusterIP
